### ISSUE TITLE
Using NEO4J_AUTH_FILE with docker compose secrets doesn't work out of the box

### ISSUE THREAD

**Issue by mateuszpawlik** [neo4j/docs-operations#1879]
I follow the documentation: https://neo4j.com/docs/operations-manual/current/docker/docker-compose-standalone/#docker-compose-secrets

Found sources here: https://github.com/neo4j/docs-operations/blob/5.x/modules/ROOT/pages/docker/docker-compose-standalone.adoc#deploy-a-neo4j-server-with-docker-secrets

With `neo4j:5.22.0` image, when I use docker compose secrets and set `NEO4J_AUTH_FILE` environment variable, neo4j service errors out with:
```
Failed to read config: Unrecognized setting. No declared setting with name: AUTH.FILE. Cleanup the config or disable 'server.config.strict_validation.enabled' to continue.
```

It seems to the a new feature. I used neo4j:5.24.2 image and get the following error:
```
Invalid value for NEO4J_AUTH: 'neo4j:averylongpassword'
```

I changed the content of my `neo4j_auth.txt` file to `neo4j/averylongpassword`, and neo4j started.

**Comment by mateuszpawlik** [comment]
It seems to the a new feature. I used neo4j:5.24.2 image and get the following error:
```
Invalid value for NEO4J_AUTH: 'neo4j:averylongpassword'
```

**Comment by mateuszpawlik** [comment]
I found `NEO4J_AUTH_PATH` variable in

https://github.com/neo4j/docker-neo4j/blob/3788f715e4d69f3df21f9c17efa5af29bd57e27d/docker-image-src/5/coredb/docker-entrypoint.sh#L615-L632

which sets initial password for Neo4j. It helps in my case, as I need it for starting Neo4j in production and load initial data from dump.

Unfortunately, I cannot find any documentation about this variable.

**Comment by renetapopova** [comment]
Sorry, it was a typo in the documentation. The key-value pair in the example file, neo4j_auth.txt ,  didn't match the one further down `--env NEO4J_AUTH=neo4j/your_password`. Fix is on the way.

**Comment by mateuszpawlik** [comment]
Thank you @renetapopova. Could  you confirm for me that `NEO4J_AUTH_FILE` is a rather new feature and which is the first version of Neo4j implementing it?
